### ISSUE TITLE
arxiv link?

### ISSUE THREAD

**Issue by samim23** [yassersouri/deep-relative-attributes#1]
hi there, this looks interesting. is there a related arxiv paper to this? would like to post it on gitxiv.com

**Comment by yassersouri** [comment]
Hi,

The extended abstract is on my website. If I ever get to do a proper full
length paper (hopefully) I will post it on arXiv and let you know.

Thanks BTW for posting my project on your amazing gitXiv webiste.

**Comment by samim23** [comment]
Great, will look at it tomorrow. Btw. excellent to see more ML coming from Iran. I´m half iranian ;-)

**Comment by erfannoury** [comment]
@samim23 YEEEESSSSSSS! I KNEW IT!
I have guessed that you might be somehow an "Iranian", but I didn't have a proof.
