### ISSUE TITLE
Suggested changes to the page

### ISSUE THREAD

**Issue by erfannoury** [yassersouri/deep-relative-attributes#2]
* *ongoing* -> WIP (or Work in Progress)

* ... I actually want to experiment how learning ... ->  ... I actually want to experiment *with* how learning ...

* This small piece of code is available here ... -> This small piece of code is available *at*

* on the 2 original datasets -> on 2 original datasets 

* The baseline will have names of -> The baseline *is named as*

* where NNN indicated what neural -> ,where NNN *indicates* what neural 

* We can see that this simple baseline outperforms the baseline by a considerable margin -> We can see that this simple baseline outperforms the _??????_ by a considerable margin

* Given that this is a scene dataset trying a network -> Given that this is a _scenes_ dataset, _utilizing_ a network

* features learned by the CaffeNet-ILSVRC2012 is not good -> features learned by the CaffeNet-ILSVRC2012 _are_ not good 

* them actually will help and is a promising direction to take. -> them _will actually_ help and is a promising direction to _follow_.

**Comment by yassersouri** [comment]
Thanks alot.
