### ISSUE TITLE
Evaulating the ranking output

### ISSUE THREAD

**Issue by erfannoury** [yassersouri/deep-relative-attributes#4]
There seems to be inconsistencies in the way @yassersouri and I evaluate the accuracy of ranking. 
Mainly when two samples are predicted as having equal rank, and they indeed happen to have the same ranking, I count it as a true positive. However, @yassersouri ignores this case completely and doesn't count neither towards reward nor loss. 
I think we should now settle on this and come up with a correct and final criteria for calculating the accuracy of ranking.

**Comment by yassersouri** [comment]
@eadeli I would really appreciate your input in this.

**Comment by eadeli** [comment]
Well, it seems that what @erfannoury is doing would be the appropriate thing (and seems logical). I could see any such case discussed in the previous papers. If the ground truth says they have a same ranking, shouldn't it be counted as TP and be rewarded? I will again see Grauman CVPR 2014 paper and try to figure out how they have dealt with it. But I guess it was not mentioned, there.

**Comment by yassersouri** [comment]
Here are the different implementations and their results on mnist regression network (evaluated for ranking).

If you see the result is different from the one I reported, it is because I retrained it and the code is stochastic (initialized with random weights).

## Yasser's Version
__accuracy__: 89.02
```python
def eval_ranking_accuracy(true_value, estimates):
    assert true_value.shape == estimates.shape
    assert len(true_value.shape) == 1
    num_samples = true_value.shape[0]
    total = 0
    correct = 0
    for i in range(num_samples):
        true_i = true_value[i]
        est_i = estimates[i]
        for j in range(i):
            true_j = true_value[j]
            est_j = estimates[j]
            
            if true_i != true_j:
                total += 1
                
                if true_i > true_j and est_i > est_j:
                    correct += 1
                if true_i < true_j and est_i < est_j:
                    correct += 1
    return float(correct) / total
```

## Erfan's Version
__acuracy__: 80.09
```python
def eval_ranking_accuracy(true_value, estimates):
    assert true_value.shape == estimates.shape
    assert len(true_value.shape) == 1
    num_samples = true_value.shape[0]
    total = 0
    correct = 0
    equal = 0
    for i in range(num_samples):
        true_i = true_value[i]
        est_i = estimates[i]
        for j in range(i):
            true_j = true_value[j]
            est_j = estimates[j]
            
            if true_i != true_j:
                total += 1
                
                if true_i > true_j and est_i > est_j:
                    correct += 1
                if true_i < true_j and est_i < est_j:
                    correct += 1
            
            if true_i == true_j:
                total += 1
                if est_i == est_j:
                    correct += 1
    return float(correct) / total
```

I have further checked that from all of the pairs only 1 pair have estimated rank exactly equal (==). So with == when cannot check the equality of estimations. Then what should we use?

**Comment by eadeli** [comment]
So, I do not undertand. You say, but one the others are not equal? Then if not equal shouldn't it be counted as loss?

**Comment by yassersouri** [comment]
They are not exactly equal because they are float numbers. And comparing
floats for their equality in this case is not fair, in my opinion.

**Comment by eadeli** [comment]
Ok. Got you... So, if you want to see if they are equal or not and isn't it better to see if the difference is less than a predefined threshold?
| predicted - groundTruth | < \tau
Also, it seems that it is better to report an error metric and not just a % of how the tanking worked. Mean Absolute Error might be more reasonable and fair...

**Comment by yassersouri** [comment]
Do you have time tomorrow? Lets talk about it on skype.

**Comment by yassersouri** [comment]
@eadeli @erfannoury As we discussed with erfan, this is certainly an issue. Proper model must be able to predict attribute strength equality. But we are not sure how to measure the fact that a network is able to do it. As we don't have much time, this might not make it into the final paper. Erfan will continue to work on this. I suggest a person with more knowledge in this regard might be able to help us.

For now we will continue to use my version of evaluation function for our experiments.

**Comment by erfannoury** [comment]
Yes, we agreed on that previous works have used Mr. Souri's evaluation method. 
However, IMO, it's a great point that we can discuss about in the paper.
The runaway counter point is that their model can predict **_relative_** attributes accurately, but no more. However our model is not only capable of predicting the **_relative_** ordering of attributes accurately (even more accurate than previous works), but also it can rank them according to their relative possession of the attribute, that is, we can even tell when two samples have relatively comparable amount of the relative attribute. Thus we can have two versions of accuracy comparisons in the paper, one with _their_ evaluation method, and one with _our_ **better** evaluation method. I can write this section of the paper if you would let me.

**Comment by yassersouri** [comment]
@erfannoury and what is the "better evaluation method". Can you implement it? Can you justify it?
Also how are you going to compare the works of others since we don't have their raw prediction values to ours on this new and "better evaluation method".

**Comment by erfannoury** [comment]
Better evaluation method should take into account the reward or loss of ranking correctly or incorrectly of two samples w.r.t. their values of the attribute. 
It's already implemented, and there is no need to justify it, it's logically correct. The other evaluation method completely ignores a whole case of relativity. 
Why not? We already have all of their codes and implementations, and if you remember we even evaluated Parikh et al.'s results using "my evaluation" and their results were much worse than one would expect.

**Comment by yassersouri** [comment]
Where is the implementation?

We absolutely need to justify it.

We only have a big zip file for the relative parts paper. And we have the predictions of "Relative Attributes" (Global method) paper for the OSR and Pubfig datasets. Other than that we don't have anything else.

**Comment by erfannoury** [comment]
We just have to add few lines to check for equality in the ground truth and then update the accuracy accordingly.

There is no need to justify it. It's a scientific matter and we are proposing an alternative evaluation method that we would be describing thoroughly and comparing to the previous evaluation method. And it is ok if we don't have access to the implementations of all other methods, we can only compare results using the alternative evaluation method on the results that we currently have access to.

**Comment by yassersouri** [comment]
Ok. Do your best.

But I think this does not have priority.

**Comment by eadeli** [comment]
Well, I agree with @erfannoury <https://github.com/erfannoury>, and it is a
good point, if we can provide a table or something to show that based on
this new evaluation we do very good, compared to for example Parikh et al.,
or others. We also need a clear definition (easy to understand and justify)
and a very smooth scenario for the experiments.
